SUBROUTINE CALMAC1(IC,ICOMP)

USE MASTERXSL
!USE TEMP_BURNUP
USE DEPLMOD
USE PARAM
USE TIMER
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFDBK.INC'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
! ADDED IN ARTOS VER. 0.2 . 2012_07_11 BY SCB.
INCLUDE 'FILES.H'
INCLUDE 'FFDM.H'

INTEGER,INTENT(IN)::IC,ICOMP

DO IT=1,NTYPE2
    DO IN=1,mnucl  
        IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE .OR. IN.EQ.ICRD) THEN  ! 2014_07_28 . pkb
        !IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE) THEN
        CONTINUE
        ELSE
            DO IG=1,NG
                MACORIGIN(ICOMP,IT,IG) = MACORIGIN(ICOMP,IT,IG) + ORIGINXS(ICOMP,IT,IN,IG) * NUCND_T(IC,IN)
            END DO
        END IF
    END DO
END DO

END SUBROUTINE