SUBROUTINE CALMAC2(IC,ICOMP)

USE MASTERXSL
!USE TEMP_BURNUP
USE PARAM
USE TIMER
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFDBK.INC'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
! ADDED IN ARTOS VER. 0.2 . 2012_07_11 BY SCB.
INCLUDE 'FILES.H'

!
!------------- PPM DERIVATIVES MACROSCOPIC XS CALCULATION -----------------
!
DO ID=1,NBORON(IC)
DO IT=1,NTYPE2
    DO IN=1,NUCNUM
        IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE .OR. IN.EQ.ICRD) THEN   ! 2014_07_28 . pkb
        !IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE) THEN
            CONTINUE
        ELSE
            DO IG=1,NG
                MACDPPM(ICOMP,IT,IG,ID) = MACDPPM(ICOMP,IT,IG,ID) + PPMDXS(ICOMP,IT,IN,IG,ID) * NUCND_T(IC,IN)
            END DO
        END IF
    END DO
END DO
END DO

!
!---------- FUEL TEMP DERIVATIVES MACROSCOPIC XS CALCULATION ---------------
!
DO ID=1,NTFUEL(IC)
DO IT=1,NTYPE2
    DO IN=1,NUCNUM
        IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE .OR. IN.EQ.ICRD) THEN   ! 2014_07_28 . pkb
        !IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE) THEN
            CONTINUE
        ELSE
            DO IG=1,NG
                MACDTF(ICOMP,IT,IG,ID) = MACDTF(ICOMP,IT,IG,ID) + TFDXS(ICOMP,IT,IN,IG,ID) * NUCND_T(IC,IN)
            END DO
        END IF
    END DO
END DO
END DO

!
!---------- MOD TEMP DERIVATIVES MACROSCOPIC XS CALCULATION ---------------
!
DO ID=1,NTMOD(IC)
DO IT=1,NTYPE2
    DO IN=1,NUCNUM
        IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE .OR. IN.EQ.ICRD) THEN   ! 2014_07_28 . pkb
        !IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE) THEN
            CONTINUE
        ELSE
            DO IG=1,NG
                MACDTM(ICOMP,IT,IG,ID) = MACDTM(ICOMP,IT,IG,ID) + TMDXS(ICOMP,IT,IN,IG,ID) * NUCND_T(IC,IN)
            END DO
        END IF
    END DO
END DO
END DO

!
!---------- MOD DENSITY DERIVATIVES MACROSCOPIC XS CALCULATION ---------------
!

DO ID=1,NDMOD(IC)
    DO IT=1,NTYPE2
        DO IN=1,NUCNUM
          IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE .OR. IN.EQ.ICRD) THEN   ! 2014_07_28 . pkb
        !IF(IN.EQ.IH2O .OR. IN.EQ.IB10 .OR. IN.EQ.IPM .OR. IN.EQ.ISM .OR. IN.EQ.II .OR. IN.EQ.IXE) THEN
                CONTINUE
            ELSE
                DO IG=1,NG
                    MACDDM(ICOMP,IT,IG,ID) = MACDDM(ICOMP,IT,IG,ID) + DMDXS(ICOMP,IT,IN,IG,ID) * NUCND_T(IC,IN)
                END DO
            END IF
        END DO
    END DO
END DO

END SUBROUTINE