#define MASTER
  SUBROUTINE CRDXS(IFFDBK,DEL,L,K,L2)

USE PARAM
USE TIMER
USE MASTERXSL
!USE TEMP_BURNUP
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB
USE ALLOCS

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
INCLUDE 'FILES.H'
INCLUDE 'XESM.H'  ! 2013_09_27 . SCB

LOGICAL::FUEL,REFL
INTEGER::ID=5,K1
INTEGER,INTENT(IN)::L,K,L2
LOGICAL,INTENT(IN)::IFFDBK
REAL,INTENT(IN)::DEL(NUMOFDXS-1)
INTEGER,DIMENSION(6,4)::INDEXBP=0, INDEXRL=0
! INDEXRL
! 1 : BOTH
! 2 : ROD IN LEFT CORNER
! 3 : ROD IN RIGHT CORNER

REAL::FACT1
REAL :: DZFAK(7,4)=0.D0, DZREL(6)=0.D0, XX=0.D0
REAL :: EPS=1.E-15
INTEGER :: IRODTYP1(6), IRODTYP2(6), IROD(6), ITORD(6)
REAL    :: CRFRAC1(6), CRFRAC2(6)
REAL, POINTER :: ADFIC(:,:), ADFICL(:,:,:), CRADF(:,:)
LOGICAL,SAVE :: FIRST=.TRUE. , FIRST2=.TRUE.

COMMON / MAS_CR_ADF / ADFIC, ADFICL, CRADF

IF(FIRST) THEN
  FIRST=.FALSE.
  CALL DMALLOC(ADFIC,NG,6)
  CALL DMALLOC(ADFICL,NG,6,4)
  CALL DMALLOC(CRADF,NG,3)
ELSE
  ADFIC=0.D0
  ADFICL=0.D0
  CRADF=0.D0
ENDIF  

FUEL = .TRUE.
REFL = .FALSE.
IRODTYP1=0; IRODTYP2=0
CRFRAC1=0.D0 ; CRFRAC2=0.D0
INDEXBP=0
INDEXRL=0

DO IC=1,6
  IRODTYP1(IC)=ABS(ASSEMCONTROL(L2,IC))
  IRODTYP2(IC)=ABS(ASSEMCONTROL(L2,IC+1))

  CRFRAC1(IC)=RODFRAC(K,IRODTYP1(IC))
  CRFRAC2(IC)=RODFRAC(K,IRODTYP2(IC))
ENDDO

IF(FLAGCRADF) THEN
  DO IC=1,6
      IF(CRFRAC1(IC).GE.EPS) THEN
          IROD(IC) = 1
      ELSE
          IROD(IC) = 0
      ENDIF
  ENDDO

  CALL GETCRADF(IROD,ITYPE,ITORD)
ELSE
  IF(FIRST2) THEN
    FIRST2=.FALSE.
    
    NCRTYPE=1
    ALLOCATE(XSRATIO(MASCOM,NCRTYPE,NTYPE2,NG))
    ALLOCATE(ADFRATIO(MASCOM,NCRTYPE,6,NG))
    
    ITORD=1
    XSRATIO=1.D0
    ADFRATIO=1.D0
  ENDIF  
  
  ITYPE=1
ENDIF

!XSRATIO(:,:,:,:)  = 1.0
!ADFRATIO(:,:,:,:) = 1.0

! 2014_08_20 . PKB
DO IC=1,6
    DZFAK(IC,4) = 0.d0
    DZFAK(IC,3) = 0.d0
    DZFAK(IC,2) = 0.d0
    DZFAK(IC,1) = 0.d0
    
    IF(IRODTYP1(IC).EQ.0)  CYCLE
    
    IF(CRFRAC1(IC).GE.0.75 .AND. CRFRAC1(IC).LE.1.0) THEN
       DZFAK(IC,4) = CRFRAC1(IC) - 0.75
       DZFAK(IC,3) = 0.25
       DZFAK(IC,2) = 0.25
       DZFAK(IC,1) = 0.25
    ELSEIF(CRFRAC1(IC).GE.0.5 .AND. CRFRAC1(IC).LE.0.75) THEN
       DZFAK(IC,3) = CRFRAC1(IC) - 0.5
       DZFAK(IC,2) = 0.25
       DZFAK(IC,1) = 0.25
    ELSEIF(CRFRAC1(IC).GE.0.25 .AND. CRFRAC1(IC).LE.0.5) THEN
       DZFAK(IC,2) = CRFRAC1(IC) - 0.25
       DZFAK(IC,1) = 0.25
    ELSEIF(CRFRAC1(IC).LE.0.25) THEN
       DZFAK(IC,1) = CRFRAC1(IC)
    ENDIF 
END DO
DZFAK(7,:) = DZFAK(1,:)

DO IK=1,4
  DO IC=1,5,2
      IF(DZFAK(IC,IK).GT.EPS .AND. DZFAK(IC+1,IK).GT.EPS) THEN
          INDEXBP(IC,IK)=1
          INDEXRL(IC,IK)=1
      ELSEIF(DZFAK(IC,IK).GT.EPS .AND. DZFAK(IC+1,IK).LE.EPS) THEN
          INDEXBP(IC,IK)=2
          INDEXRL(IC,IK)=2
      ELSEIF(DZFAK(IC,IK).LE.EPS .AND. DZFAK(IC+1,IK).GT.EPS) THEN
          INDEXBP(IC,IK)=3
          INDEXRL(IC,IK)=3
      END IF
  END DO

  DO IC=2,6,2
      IF(DZFAK(IC,IK).GT.EPS .AND. DZFAK(IC+1,IK).GT.EPS) THEN
          INDEXBP(IC,IK)=1
          INDEXRL(IC,IK)=1
      ELSEIF(DZFAK(IC,IK).GT.EPS .AND. DZFAK(IC+1,IK).LE.EPS) THEN
          INDEXBP(IC,IK)=3
          INDEXRL(IC,IK)=2
      ELSEIF(DZFAK(IC,IK).LE.EPS .AND. DZFAK(IC+1,IK).GT.EPS) THEN
          INDEXBP(IC,IK)=2
          INDEXRL(IC,IK)=3
      END IF
  END DO
ENDDO

! ADDED END
!
!! 2014_08_20 . SCB
!IF(DZFAK

ORIGINCR(:,L,K,:)=0.D0   ! 2014_08_20 . SCB
PPMCR(:,L,K,:)=0.D0   ! 2014_08_20 . SCB
DMDCR(:,L,K,:)=0.D0   ! 2014_08_20 . SCB

#ifdef MASTER
DO IK=1,4
  DO IC=1,6
      IF(DZFAK(IC,IK).GT.EPS .AND. DZFAK(IC+1,IK).GT.EPS) THEN
          INDEXBP(IC,IK)=1
          INDEXRL(IC,IK)=1
      ELSEIF(DZFAK(IC,IK).GT.EPS .AND. DZFAK(IC+1,IK).LE.EPS) THEN
          INDEXBP(IC,IK)=2
          INDEXRL(IC,IK)=2
      ELSEIF(DZFAK(IC,IK).LE.EPS .AND. DZFAK(IC+1,IK).GT.EPS) THEN
          INDEXBP(IC,IK)=3
          INDEXRL(IC,IK)=3
      END IF
  ENDDO  
END DO

K1 = K

IAT=IASSYTYP(L)
ICOMP=ICOMPNUMZ(K,IAT)
ICOMP1=ICOMPNUMZ(K1,IAT)

200 CONTINUE

IF(.NOT.IFMASFUEL(ICOMP1)) THEN
    FUEL   = .FALSE.    
    REFL   = .TRUE.
    ICOMP2 = ICOMP1
ENDIF 

IF(REFL) THEN
    IF(K.GT.(NZ/2)) THEN
        K1=K1-1
    ELSE
        K1=K1+1
    ENDIF

    IF(K1.GT.NZ .OR. K1.LT.1) THEN
        ICOMP=ICOMPNUMZ(K,IAT)
        RETURN
    END IF

    ICOMP1=ICOMPNUMZ(K1,IAT)

    IF(IFMASFUEL(ICOMP1)) THEN
        ICOMP=ICOMP1
    ELSE
        GOTO 200
    ENDIF
ENDIF

! 2014_08_22 . scb for CR ADF
DO IC=1,3
  DO M=1,NG
    ADFIC(M,IC)=XSADF(IC+3,M,L,K)
    ADFIC(M,IC+3)=XSADF(IC,M,L,K)
  
    ADFICL(M,IC,:)=0.D0
      
    !CRADF(M,IC)=ORIGINADF_CR(ICOMP,M,IC) + PPMDADF_CR(ICOMP,M,IC)*DEL(1) + DMDADF_CR(ICOMP,M,ID,IC)*DEL(3)
    CRADF(M,IC)=ORIGINADF_CR(ICOMP,M,IC)
  ENDDO  
ENDDO
! ADDED END

DO IK=1,4
  DO IC=1,6
    IPB=0
    IPE=0
    FACT1 = 0.1666666666666667
    FACT2 = 4.D0
    TEMP=DZFAK(IC,IK)*DZFAK(IC+1,IK)
    IF(INDEXBP(IC,IK).EQ.1 .AND. TEMP.GT.EPS .AND. IRODTYP1(IC).NE.IRODTYP2(IC)) THEN
      FACT1=0.0833333333   
      FACT2=2.D0
      IPE=1
    ELSEIF(INDEXRL(IC,IK).EQ.3) THEN
      IPB=1
      IPE=1
    ENDIF
    
    DO IP=IPB,IPE
      ICS=IC+IP
      IF(ICS.EQ.7) ICS=1
! 2014_08_22 . SCB FOR CR ADF
      IL=INDEXBP(IC,IK)
      DO M=1,NG
        ADFICL(M,IC,IK)=ADFICL(M,IC,IK) + FACT2*( (0.25-DZFAK(ICS,IK))*ADFIC(M,IC) + DZFAK(ICS,IK)*CRADF(M,IL) )        
      ENDDO
! ADDED END

      IF(DZFAK(ICS,IK).GT.0) THEN
        FAC = DZFAK (ICS,IK) * FACT1
        XX = RODFRAC(K,ASSEMCONTROL(L2,ICS))
        !XX=1.D0
        FAC = FAC*(0.18314*XX**2+0.16834*xx+0.64852)
        DO M=1,NG
          DO IT=1,NTYPE2
              IF(REFL) THEN
                IF(IT.EQ.NUFS .OR. IT.EQ.FISS .OR. IT.EQ.KAPA) THEN
                  CYCLE
                ELSE
                  ORIGINCR(M,L,K,IT) = ORIGINCR(M,L,K,IT)&
                                     + OCRDXS(ICOMP,IT,M,IL)*FAC*XSRATIO(ICM2ICA(ICOMP),ITYPE,IT,M)
                ENDIF
              ELSE
                ORIGINCR(M,L,K,IT) = ORIGINCR(M,L,K,IT)&
                                   + OCRDXS(ICOMP,IT,M,IL)*FAC*XSRATIO(ICM2ICA(ICOMP),ITYPE,IT,M)
                PPMCR(M,L,K,IT) = PPMCR(M,L,K,IT)&
                                + PPMDXS_H(ICOMP,IT,M,IL)*FAC*XSRATIO(ICM2ICA(ICOMP),ITYPE,IT,M) 
              ENDIF
          END DO
            IF(IC.EQ.6) THEN
              DO ICC=1,6
                ADFICL(M,ICC,IK)=ADFICL(M,ICC,IK)*ADFRATIO(ICM2ICA(ICOMP),ITYPE,ITORD(ICC),M)   ! 2014_09_01 . PKB THE CRADF WAS IMPLEMENTED
              ENDDO
            ENDIF 
        ENDDO
      
        IF(IFFDBK .AND. FUEL) THEN
          DO M=1,NG 
            DO IT=1,NTYPE2           
              DMDCR(M,L,K,IT) = DMDCR(M,L,K,IT)&
                              + DMDXS_H(ICOMP,IT,M,IL,ID)*FAC*XSRATIO(ICM2ICA(ICOMP),ITYPE,IT,M) 
            ENDDO                    
          ENDDO
        ENDIF      
      ENDIF    
    ENDDO           
  END DO  
END DO

! 2014_08_22 . SCB
DO IC=1,3
  IC1=IC+3
  DO M=1,NG
    XSADF(IC1,M,L,K)=0.25D0*(ADFICL(M,IC,1)+ADFICL(M,IC,2)+ADFICL(M,IC,3)+ADFICL(M,IC,4))
    XSADF(IC,M,L,K)=0.25D0*(ADFICL(M,IC1,1)+ADFICL(M,IC1,2)+ADFICL(M,IC1,3)+ADFICL(M,IC1,4))
  ENDDO  
ENDDO

DO IC=1,6
  IC1=IC-1
  IF(IC1.EQ.0) IC1=6
  DO M=1,NG
    XSCDF(IC,M,L,K)=0.5D0*(XSADF(IC,M,L,K)+XSADF(IC1,M,L,K))
  ENDDO
ENDDO
! ADDED END

IF(REFL)  ICOMP=ICOMPNUMZ(K,IAT)

#else
FACT1=0.0833333333   
DO IK=1,4
  DO IC=1,6
    DO IP=0,1
      ICS=IC+IP
      IF(ICS.EQ.7) ICS=1
      IF(DZFAK(ICS,IK).GT.0) THEN
        FAC = DZFAK (ICS,IK) * FACT1
        XX = RODFRAC(K,ASSEMCONTROL(L,ICS))
        !XX=1.D0
        FAC = FAC*(0.18314*XX**2+0.16834*xx+0.64852)
        DO M=1,NG
          DO IT=1,NTYPE2
              ORIGINCR(M,L,K,IT) = ORIGINCR(M,L,K,IT)&
                                 + OCRDXS(ICOMP,IT,M,INDEXBP(ICS))*FAC
              PPMCR(M,L,K,IT) = PPMCR(M,L,K,IT)&
                              + PPMDXS_H(ICOMP,IT,M,INDEXBP(ICS))*FAC
          END DO
        ENDDO
      
        IF(IFFDBK) THEN
          DO M=1,NG 
            DO IT=1,NTYPE2           
              DMDCR(M,L,K,IT) = DMDCR(M,L,K,IT)&
                              + DMDXS_H(ICOMP,IT,M,INDEXBP(ICS),ID)*FAC
            END DO        
          ENDDO
        ENDIF      
      ENDIF    
    ENDDO    
  END DO
END DO
#endif

!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!DO IK=1,4
!  DO IC=1,6
!    IF(DZFAK(IC,IK).GT.0) THEN
!      FAC = DZFAK (IC,IK) * FACT1
!      XX = RODFRAC(K,ASSEMCONTROL(L,IC))
!      !XX=1.D0
!      FAC = FAC*(0.18314*XX**2+0.16834*xx+0.64852)
!      DO M=1,NG
!        DO IT=1,NTYPE2
!            ORIGINCR(M,L,K,IT) = ORIGINCR(M,L,K,IT)&
!                               + OCRDXS(ICOMP,IT,M,INDEXBP(IC))*FAC
!            PPMCR(M,L,K,IT) = PPMCR(M,L,K,IT)&
!                            + PPMDXS_H(ICOMP,IT,M,INDEXBP(IC))*FAC
!        END DO
!      ENDDO
!      
!      IF(IFFDBK) THEN
!        DO M=1,NG
!          DO IT=1,NTYPE2           
!            DMDCR(M,L,K,IT) = DMDCR(M,L,K,IT)&
!                            + DMDXS_H(ICOMP,IT,M,INDEXBP(IC),ID)*FAC
!          END DO        
!        ENDDO
!      ENDIF      
!    ENDIF    
!  END DO
!END DO

END SUBROUTINE