! 2014_08_07 . SCB
SUBROUTINE DUPDXS_AXIAL(DCOOL,BASED,ICOMP,M,L,K)

USE PARAM
USE TIMER
USE MASTERXSL
!USE TEMP_BURNUP
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
INCLUDE 'FILES.H'
INCLUDE 'XESM.H'  ! 2013_09_27 . SCB

INTEGER,INTENT(IN)::M,L,K
REAL,INTENT(IN)::DCOOL,BASED
INTEGER :: NUM
REAL::FACT,FACT2,DIV
REAL::H2O,B10

NUM=ICM2ICA(ICOMP)-MASCOM-3

DIV = DCOOL/BASED
H2O = RFND(NUM,RH2O)*DIV

FACT  = 3.2992605D-07
FACT2 = PPM * FACT
B10   = H2O * FACT2

DELH2O = H2O - RFND(NUM,RH2O)
DELB10 = B10 - RFND(NUM,RB10)

!XSTRFDCSP(M,L,K) = XSTRFDCSP(M,L,K)&
XSTRF(M,L,K) = XSTRF(M,L,K)&
             + AXIAL(NUM,RH2O,TRAN,M)*DELH2O + AXIAL(NUM,RB10,TRAN,M)*DELB10
!XSTRF(M,L,K)=XSTRFDCSP(M,L,K)   ! 2013_07_17 . SCB
!XSDF(M,L,K)=1.D0/(3.D0*XSTRFDCSP(M,L,K))
XSDF(M,L,K)=1.D0/(3.D0*XSTRF(M,L,K))
XSDF2(M,L,K)=9.D0/7.D0*XSDF(M,L,K)   ! 2013_07_15 . SCB

XSAF(M,L,K) = XSAF(M,L,K)&
                 + AXIAL(NUM,RH2O,ABSO,M)*DELH2O + AXIAL(NUM,RB10,ABSO,M)*DELB10

DO MS=SIGSMS(M,ICOMP),SIGSME(M,ICOMP)
    IF(SIGSMS(M,ICOMP) .EQ. SIGSME(M,ICOMP)) THEN
        CONTINUE
    ELSE
        XSSF(MS,M,L,K) = XSSF(MS,M,L,K)&
                 + AXIAL(NUM,RH2O,SCA,M)*DELH2O + AXIAL(NUM,RB10,SCA,M)*DELB10
        XSSF(2,2,L,K)  = 0.
    END IF 
ENDDO

END SUBROUTINE
! ADDED END