SUBROUTINE MAS_ALLOC1(CNUM,NAXIAL,NRADIAL)

USE MASTERXSL
!USE TEMP_BURNUP
USE PARAM

INCLUDE 'GLOBAL.H'
INCLUDE 'BENCH.H'
INCLUDE 'XSEC.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'CARDS.H'

INTEGER,INTENT(IN)::CNUM,NAXIAL,NRADIAL

!ALLOCATE(CNAME(CNUM))
ALLOCATE(CNAME(ncomp))   ! 2014_07_31 . scb
ALLOCATE(NBURN(CNUM))
ALLOCATE(NDER(CNUM))
ALLOCATE(NDMOD(CNUM))

ALLOCATE(NADF(CNUM))
ALLOCATE(NDUM(CNUM))
! 2014_07_31 . scb
!ALLOCATE(RPPM(CNUM))
!ALLOCATE(RTF(CNUM))
!ALLOCATE(RTM(CNUM))
!ALLOCATE(RDM(CNUM))
ALLOCATE(RPPM(NCOMP))
ALLOCATE(RTF(NCOMP))
ALLOCATE(RTM(NCOMP))
ALLOCATE(RDM(NCOMP))
! added end
ALLOCATE(RPRESS(CNUM))
ALLOCATE(RFND(NAXIAL,NRC))
ALLOCATE(RFPPM(NRADIAL))
ALLOCATE(RFTEMP(NRADIAL))
ALLOCATE(RFMOD(NRADIAL))   ! 2014_08_07 . SCB
ALLOCATE(RFPRES(NRADIAL))
ALLOCATE(AXIAL(NAXIAL,NRC,NTYPE2,NG))
ALLOCATE(RADIAL(NRADIAL,NTYPE2,NG))
ALLOCATE(DTMRADIAL(NRADIAL,NTYPE2,NG))
ALLOCATE(MACAXIAL(NAXIAL,NRC,NTYPE2,NG))

RFND(:,:)         = 0.
AXIAL(:,:,:,:)    = 0.
MACAXIAL(:,:,:,:) = 0.
RADIAL(:,:,:)     = 0.
DTMRADIAL(:,:,:)  = 0.

! 2014_07_31 . scb
rppm=0.d0
rtf=0.d0
rtm=0.d0
rdm=0.d0
! added end

! 2014_08_07 . SCB
ALLOCATE(IXSDERV(NRADIAL))
IXSDERV=0
! ADDED END



END SUBROUTINE