SUBROUTINE RADIAL_M2A(ICOMP,PART)

USE MASTERXSL
!USE TEMP_BURNUP
USE PARAM

INCLUDE 'GLOBAL.H'
INCLUDE 'BENCH.H'
INCLUDE 'XSEC.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'CARDS.H'

INTEGER,INTENT(IN)::ICOMP,PART
INTEGER::INDEX

IF(NG .EQ. 2) THEN
    SIGSMS(1,ICOMP) = 1
    SIGSMS(2,ICOMP) = 1
    SIGSME(1,ICOMP) = 1
    SIGSME(2,ICOMP) = 2
END IF

IF(PART.EQ.RCORNER) THEN
    INDEX=1
ELSEIF(PART.EQ.REDGE) THEN
    INDEX=2
ELSEIF(PART.EQ.RNOOK) THEN
    INDEX=3
ENDIF

DO IG=1,NG
    SIGTR(IG,ICOMP) = RADIAL(INDEX,TRAN,IG)
    SIGD(IG,ICOMP)  = 1/(3*SIGTR(IG,ICOMP))
    SIGA(IG,ICOMP)  = RADIAL(INDEX,ABSO,IG)
    SIGNF(IG,ICOMP) = 0.
    SIGKF(IG,ICOMP) = 0.
    SIGF(IG,ICOMP)  = 0.    ! 2014_07_31 . scb
    DO MS=1,IG
        IF(MS .EQ. IG) THEN
            CONTINUE
        ELSE
            SIGSM(MS,IG,ICOMP) = RADIAL(INDEX,SCA,IG)
            SIGSM(2,2,ICOMP)   = 0.  ! 2014_07_28_PKB
        END IF
    END DO
END DO

SIGCHI(1,ICOMP) = 1.
SIGCHI(2,ICOMP) = 0.

! 2014_08_05 . pkb
DO IG=1,NG
    DSIGD_TR(DTM,IG,ICOMP) = DTMRADIAL(INDEX,TRAN,IG)
    DSIGT_A(DTM,IG,ICOMP)  = DTMRADIAL(INDEX,ABSO,IG)
    DSIGNF(DTM,IG,ICOMP)   = 0.
    DSIGKF(DTM,IG,ICOMP)   = 0.
    DO MS=1,IG
        IF(MS .EQ. IG) THEN
            CONTINUE
        ELSE
            DSIGSM(MS,DTM,IG,ICOMP) = DTMRADIAL(INDEX,SCA,IG)
            DSIGSM(2,DTM,2,ICOMP)   = 0.
        END IF
    END DO
END DO
! added end

END SUBROUTINE