SUBROUTINE READAXIAL(INDEV,PART)

USE MASTERXSL
!USE TEMP_BURNUP
USE PARAM

INCLUDE 'GLOBAL.H'
INCLUDE 'BENCH.H'
INCLUDE 'XSEC.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'CARDS.H'

INTEGER,INTENT(IN)::INDEV,PART
INTEGER::INDEX
REAL::TEMP,TEMP1(NRC)

IF(PART.EQ.RTOP) THEN
    INDEX=2
ELSEIF(PART.EQ.RBOTTOM) THEN
    INDEX=1
ENDIF

READ(INDEV,*) RFND(INDEX,RH2O)
DO IC=1,NRC
    DO IG=1,NG
        READ(INDEV,*) AXIAL(INDEX,IC,ABSO,IG),AXIAL(INDEX,IC,TRAN,IG),TEMP,AXIAL(INDEX,IC,SCA,IG)
    END DO
END DO

TEMP1(:) = AXIAL(INDEX,:,SCA,1)
AXIAL(INDEX,:,SCA,2) = TEMP1(:)
AXIAL(INDEX,:,SCA,1) = 0.

END SUBROUTINE