!SUBROUTINE READRADIAL(INDEV,PART)
SUBROUTINE READRADIAL(INDEV,PART,IXS)  ! 2014_08_07 . SCB

USE MASTERXSL
!USE TEMP_BURNUP
USE PARAM

INCLUDE 'GLOBAL.H'
INCLUDE 'BENCH.H'
INCLUDE 'XSEC.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'CARDS.H'

INTEGER,INTENT(IN)::INDEV,PART
INTEGER,INTENT(IN) :: IXS  ! 2014_08_07 . SCB
INTEGER::INDEX

IF(PART.EQ.RCORNER) THEN
    INDEX=1
ELSEIF(PART.EQ.REDGE) THEN
    INDEX=2
ELSEIF(PART.EQ.RNOOK) THEN
    INDEX=3
ENDIF

IXSDERV(INDEX)=IXS  ! 2014_08_07 . SCB

READ(INDEV,*) RFPPM(INDEX),RFTEMP(INDEX),RFPRES(INDEX)
RFMOD(INDEX)=FDENS (RFTEMP(INDEX))  ! 2014_08_07 . SCB
!RFMOD(INDEX)=658.0294    ! 2014_08_07 . SCB
!RFMOD(INDEX)=DENSTY (RFTEMP(INDEX),RFPRES(INDEX))  ! 2014_08_07 . SCB
RFMOD(INDEX)=1.D0/TAF(101,RFPRES(INDEX)*1.E5,RFTEMP(INDEX))  ! 2014_08_07 . SCB

DO IG=1,NG
    READ(INDEV,*) RADIAL(INDEX,ABSO,IG)
END DO
DO IG=1,NG
    READ(INDEV,*) DTMRADIAL(INDEX,ABSO,IG)
END DO

DO IG=1,NG
    READ(INDEV,*) RADIAL(INDEX,TRAN,IG)
END DO
DO IG=1,NG
    READ(INDEV,*) DTMRADIAL(INDEX,TRAN,IG)
END DO

DO IG=2,NG
    READ(INDEV,*) RADIAL(INDEX,SCA,IG)
END DO
DO IG=2,NG
    READ(INDEV,*) DTMRADIAL(INDEX,SCA,IG)
END DO

END SUBROUTINE