SUBROUTINE READCCR(INDEV)

USE PARAM
USE MASTERXSL 

INCLUDE 'GLOBAL.H'     
INCLUDE 'FILES.H'
INCLUDE 'CARDS.H'      
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'GEOMH.H'
INCLUDE 'GEOMHFC.H'
INCLUDE 'ITRCNTL.H'  
INCLUDE 'FF.H'    
INCLUDE 'THCNTL.INC'
INCLUDE 'PERTURB.INC'
INCLUDE 'THLINK.INC' ! FREK/MARS

INTEGER,INTENT(IN)::INDEV
LOGICAL::FLAG1 = .FALSE.
LOGICAL::FLAG2 = .FALSE.
LOGICAL::FLAG3 = .FALSE.

INTEGER :: TEMP(6)
INTEGER :: APINI   ! 2014_08_20 . SCB

CALL RODALLOC2

IR = 0
DO WHILE(IR .LT. NXROD)
    READ(INDEV,'(A512)') ONELINE
    NXCOL=NFIELDS(ONELINE)
    IF(SC(1).EQ.'!' .OR. NXCOL.EQ.0) GO TO 200 !SKIP A LINE
    DO I=1,MXNCOL
        IF(SC(I) .NE. ' ') THEN
            IASCII = ICHAR(SC(I))
            IF((IASCII-48)*(IASCII-57) .LE. 0) THEN
                GO TO 100 !NUMERIC
            ELSE
                BACKSPACE(INDEV)
                GO TO 300 !STRING
            ENDIF
        END IF
    END DO
100 CONTINUE
    IR = IR+1
    READ(ONELINE,*) (CORNERPOS(IR,IC),IC=1,NXCOL2(IR))
200 CONTINUE
ENDDO

300 CONTINUE
! ANGULAR POINT INDEXING START FROM HERE
! FIRST POINT INDEXING

IP = 1
APINI = 1
INDEX = MINCOL
DO IR=1,NXRAD
    DO I=1,INDEX
        APONE(IP) = APINI
        IP = IP + 1
    END DO
    IF(INDEX.EQ.MAXCOL-1 .OR. FLAG1) THEN
        INDEX = INDEX - 1
        FLAG1 = .TRUE.
    ELSE
        INDEX = INDEX + 1
    END IF
    APINI = APINI + 2
END DO

IP = 1
APINI = 1
INDEX = MINCOL
DO IR=1,NXRAD
    DO I=1,INDEX
        APTWO(IP) = APINI
        APINI = APINI + 1
        IP = IP + 1
    END DO
    IF(INDEX.EQ.MAXCOL-1) THEN
        INDEX = INDEX - 1
        APINI = 2
        FLAG2 = .TRUE.
    ELSE IF(FLAG2) THEN
        INDEX = INDEX - 1
        APINI = 2
    ELSE
        INDEX = INDEX + 1
        APINI = 1
    END IF
END DO

! OTHER POINT INDEXING
K=1
IF(NASSEM.EQ.1) K=2   ! 2014_08_20 . SCB
IP = 1
INDEX = MINCOL
DO IR=1,NXRAD
    DO I=1,INDEX
        IX = APONE(IP)
        IY = APTWO(IP)
        IF(K.EQ.1) THEN
            ASSEMCONTROL(IP,1) = CORNERPOS(IX,IY)
            ASSEMCONTROL(IP,2) = CORNERPOS(IX+1,IY+1)
            ASSEMCONTROL(IP,3) = CORNERPOS(IX+2,IY+1)
            ASSEMCONTROL(IP,4) = CORNERPOS(IX+3,IY+1)
            ASSEMCONTROL(IP,5) = CORNERPOS(IX+2,IY)
            ASSEMCONTROL(IP,6) = CORNERPOS(IX+1,IY)
        ELSEIF(K.EQ.2) THEN
            ASSEMCONTROL(IP,1) = CORNERPOS(IX,IY)
            ASSEMCONTROL(IP,2) = CORNERPOS(IX+1,IY+1)
            ASSEMCONTROL(IP,3) = CORNERPOS(IX+2,IY+1)
            ASSEMCONTROL(IP,4) = CORNERPOS(IX+3,IY)
            ASSEMCONTROL(IP,5) = CORNERPOS(IX+2,IY)
            ASSEMCONTROL(IP,6) = CORNERPOS(IX+1,IY) 
        ELSEIF(K.EQ.3) THEN
            ASSEMCONTROL(IP,1) = CORNERPOS(IX,IY)
            ASSEMCONTROL(IP,2) = CORNERPOS(IX+1,IY)
            ASSEMCONTROL(IP,3) = CORNERPOS(IX+2,IY)
            ASSEMCONTROL(IP,4) = CORNERPOS(IX+3,IY-1)
            ASSEMCONTROL(IP,5) = CORNERPOS(IX+2,IY-1)
            ASSEMCONTROL(IP,6) = CORNERPOS(IX+1,IY-1)           
        ENDIF
        TEMP(:)=ASSEMCONTROL(IP,:)
        DO IC=1,5
            ASSEMCONTROL(IP,IC)=TEMP(IC+1)
        END DO
        ASSEMCONTROL(IP,6)=TEMP(1)
        ASSEMCONTROL(IP,7)=ASSEMCONTROL(IP,1)
        IP = IP + 1
    END DO
    
    IF(NASSEM.EQ.1) EXIT   ! 2014_08_20 . SCB
    
    IF(FLAG3) THEN
        INDEX = INDEX - 1
        K=3
    ELSE
        INDEX = INDEX + 1
        K=1
    END IF
    IF(INDEX.EQ.MAXCOL-1) THEN
        FLAG3 = .TRUE.
        K=2
    ENDIF
END DO

! ANGULAR POINT INDEXING FINISHED

END SUBROUTINE