SUBROUTINE READXS1(IC,ICOMP)

USE MASTERXSL
!USE TEMP_BURNUP
USE PARAM
USE TIMER
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFDBK.INC'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
! ADDED IN ARTOS VER. 0.2 . 2012_07_11 BY SCB.
INCLUDE 'FILES.H'
INCLUDE 'FFDM.H'

INTEGER,INTENT(IN)::IC,ICOMP
REAL :: KLO, KHI, a

!-------------------------------------
!        EXTRAPOLATION START
!-------------------------------------

IF (BUP.GT.BURNSTEP(IC,NBURN(IC))) THEN
    KLO = NBURN(IC)-2
    AFRAC1 = 0.
    AFRAC3 = (BUP-BURNSTEP(IC,NBURN(IC)-1))/(BURNSTEP(IC,NBURN(IC))-BURNSTEP(IC,NBURN(IC)-1))
    AFRAC2 = 1.-AFRAC3
!    RETURN
ELSE IF (BUP.LT.BURNSTEP(IC,1)) THEN
    KLO = 1.
    AFRAC2 = (BUP-BURNSTEP(IC,1))/(BURNSTEP(IC,2)-BURNSTEP(IC,1))
    AFRAC1 = 1.-AFRAC2
    AFRAC3 = 0.
!    RETURN
END IF

!-------------------------------------
!        INTERPOLATION START
!-------------------------------------

IF(BUP .LT. BURNSTEP(IC,2)) THEN
    KLO = 1
    KHI = 2
    GOTO 280
ELSE IF(BUP .GT. BURNSTEP(IC,NBURN(IC)-2)) THEN
    KLO = NBURN(IC)-2
    KHI = NBURN(IC)-1
    GOTO 280
END IF

KLO = 2
KHI = NBURN(IC)-2

1000 IF(KHI-KLO.GT.1) THEN
        K=(KHI+KLO)/2
        IF(BURNSTEP(IC,K).GT.BUP) THEN
           KHI=K
        ELSE
           KLO=K
        ENDIF
        GOTO 1000       
     ENDIF 

280 CONTINUE
H=BURNSTEP(IC,KHI)-BURNSTEP(IC,KLO)
IF(H.EQ.0) THEN
   WRITE(*,*) 'SOMETHING IS WRONG'
ENDIF

if (nburn(ic)>=3) then    ! add 2017.2.1 jjh    

AB1 = BUP
A1  = BURNSTEP(IC,KLO)
A2  = BURNSTEP(IC,KHI)
A3  = BURNSTEP(IC,KHI+1)
 
A12 = A1 - A2
A21 = -A12
A23 = A2 - A3
A32 = -A23
A31 = A3 - A1
A13 = -A31
XA1 = AB1-A1
XA2 = AB1-A2
XA3 = AB1-A3
AFRAC1 = XA2*XA3/(A12*A13)
AFRAC2 = XA1*XA3/(A21*A23)
AFRAC3 = XA1*XA2/(A31*A32)


DO IG=1,NG
    DO IN=1,NUCNUM
        DO IT=1,NTYPE2                 ! 2016.9.22. jjh
      !        DO IT=1,NTYPE1
            ORIGINXS(ICOMP,IT,IN,IG) = AFRAC1*BASEXS(IC,IT,KLO,IN,IG)&
                                     + AFRAC2*BASEXS(IC,IT,KLO+1,IN,IG)&
                                     + AFRAC3*BASEXS(IC,IT,KLO+2,IN,IG)
        END DO
!        ORIGINXS(ICOMP,ABSO,IN,IG) = ORIGINXS(ICOMP,CAPT,IN,IG)+ORIGINXS(ICOMP,FISS,IN,IG)    ! 2016.9.22. jjh
        ORIGINXS(ICOMP,KAPA,IN,IG) = ORIGINXS(ICOMP,FISS,IN,IG)*KAPPA_T(IC,IN,IG)
    END DO
END DO

! 2014_07_28 . PKB
!IF(RECT) THEN
!    DO IG=1,NG
!        DO IT=1,NTYPE1
!            ORIGINXS(ICOMP,IT,ICRD,IG) = AFRAC1*BASECRDXS(IC,IT,KLO,IG)&
!                                       + AFRAC2*BASECRDXS(IC,IT,KLO+1,IG)&
!                                       + AFRAC3*BASECRDXS(IC,IT,KLO+2,IG)
!        END DO
!        ORIGINXS(ICOMP,ABSO,ICRD,IG) = ORIGINXS(ICOMP,CAPT,ICRD,IG)+ORIGINXS(ICOMP,FISS,ICRD,IG)
!        ORIGINXS(ICOMP,KAPA,ICRD,IG) = ORIGINXS(ICOMP,FISS,ICRD,IG)*KAPPA_T(IC,ICRD,IG)
!    END DO
!ELSE
!    DO L=1,3
!        DO IG=1,NG
!            DO IT=1,NTYPE1
!                OCRDXS(ICOMP,IT,IG,L) = AFRAC1*BASECRDXS_H(IC,IT,KLO,IG,L)&
!                                      + AFRAC2*BASECRDXS_H(IC,IT,KLO+1,IG,L)&
!                                      + AFRAC3*BASECRDXS_H(IC,IT,KLO+2,IG,L)
!            END DO
!            OCRDXS(ICOMP,ABSO,IG,L) = OCRDXS(ICOMP,CAPT,IG,L)+OCRDXS(ICOMP,FISS,IG,L)
!            !OCRDXS(ICOMP,KAPA,IG,L) = OCRDXS(ICOMP,FISS,IG,L)*KAPPA_T(IC,ICRD,IG)
!            OCRDXS(ICOMP,KAPA,IG,L) = OCRDXS(ICOMP,FISS,IG,L)*CRDKAPPA(IC,IG,L)  ! 2014_08_20 . pkb
!        END DO
!    END DO    
!END IF
! ADDED END

else if (nburn(ic)==2) then
  klo=1  
  DO IG=1,NG
    DO IN=1, NUCNUM
        DO IT=1, NTYPE2
           a = 0.d0
           a = (BASEXS(IC,IT,KLO+1,IN,IG) - BASEXS(IC,IT,KLO,IN,IG)) / H
           ORIGINXS(ICOMP,IT,IN,IG) = BASEXS(IC,IT,KLO,IN,IG) + A*BUP
        END DO
        ORIGINXS(ICOMP,KAPA,IN,IG) = ORIGINXS(ICOMP,FISS,IN,IG)*KAPPA_T(IC,IN,IG)
    END DO
  END DO
    
end if

END SUBROUTINE