SUBROUTINE READCRADF(INDEV2,ICRADF)

USE PARAM
USE MASTERXSL 

INCLUDE 'GLOBAL.H'     
INCLUDE 'FILES.H'
INCLUDE 'CARDS.H'      
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'GEOMH.H'
INCLUDE 'GEOMHFC.H'
INCLUDE 'ITRCNTL.H'  
INCLUDE 'FF.H'    
INCLUDE 'THCNTL.INC'
INCLUDE 'PERTURB.INC'
INCLUDE 'THLINK.INC' ! FREK/MARS

LOGICAL::FIRST=.TRUE.
CHARACTER::TEMP*5
INTEGER,INTENT(IN)::INDEV2
REAL::DUMMY

IF(ICRADF.NE.0) THEN
  NCRTYPE=1
  ALLOCATE(ICFG(NCRTYPE,12))
  ALLOCATE(TYPENAME(MASCOM,NCRTYPE))
  ALLOCATE(XSRATIO(MASCOM,NCRTYPE,NTYPE2,NG))
  
  ICFG=1
  XSRATIO(:,:,:,:) = 1.
  
  RETURN
ENDIF

READ(INDEV2,'(A512)') ONELINE
READ(ONELINE,*) TEMP,NG,NCRTYPE

ALLOCATE(ICFG(NCRTYPE,12))
ALLOCATE(TYPENAME(MASCOM,NCRTYPE))
ALLOCATE(XSRATIO(MASCOM,NCRTYPE,NTYPE2,NG))
ALLOCATE(ADFRATIO(MASCOM,NCRTYPE,6,NG))

XSRATIO(:,:,:,:) = 1.

DO IC=1,MASCOM
    ITYPE=0
    IF(FIRST) THEN
        FIRST=.FALSE.
    ELSE
        CALL SKIP(INDEV2,1)
    ENDIF
    DO I=1,NCRTYPE
        ITYPE=ITYPE+1
        READ(INDEV2,*) TYPENAME(IC,ITYPE), (ADFRATIO(IC,ITYPE,IT,1),IT=1,6)
        READ(INDEV2,*) (ADFRATIO(IC,ITYPE,IT,2),IT=1,6)
        READ(INDEV2,*) XSRATIO(IC,ITYPE,TRAN,1),XSRATIO(IC,ITYPE,ABSO,1),XSRATIO(IC,ITYPE,FISS,1),XSRATIO(IC,ITYPE,NUFS,1),XSRATIO(IC,ITYPE,SCA,2)
        READ(INDEV2,*) XSRATIO(IC,ITYPE,TRAN,2),XSRATIO(IC,ITYPE,ABSO,2),XSRATIO(IC,ITYPE,FISS,2),XSRATIO(IC,ITYPE,NUFS,2),DUMMY
    ENDDO
ENDDO

! 2014_08_29 . PKB ADDED
DO IT=1,NCRTYPE
    READ(TYPENAME(1,IT),'(6I1)') (ICFG(IT,IC),IC=1,6)
    DO IC=1,6
        ICFG(IT,IC+6) = ICFG(IT,IC)
    ENDDO
ENDDO
! ADDED END

END SUBROUTINE