SUBROUTINE RODALLOC1

USE MASTERXSL

INCLUDE 'GEOM.H'

ALLOCATE(NXCOL2(NXROD))
ALLOCATE(IRODS(NXROD))
ALLOCATE(IRODE(NXROD))
ALLOCATE(RODFRAC_H(NZ,NRODTYP))

NXCOL2(:)         = 0
IRODS(:)          = 0
IRODE(:)          = 0
RODFRAC_H(:,:)    = 0.

END SUBROUTINE