SUBROUTINE RODALLOC2

USE PARAM
USE MASTERXSL 

INCLUDE 'GLOBAL.H'     
INCLUDE 'FILES.H'
INCLUDE 'CARDS.H'      
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'GEOMH.H'
INCLUDE 'GEOMHFC.H'
INCLUDE 'ITRCNTL.H'  
INCLUDE 'FF.H'    
INCLUDE 'THCNTL.INC'
INCLUDE 'PERTURB.INC'
INCLUDE 'THLINK.INC' ! FREK/MARS

MAXCOL = NXCOL2(1)
MINCOL = NXCOL2(1)
DO I=1,NXROD
    IF(MAXCOL .LT. NXCOL2(I)) THEN
        MAXCOL = NXCOL2(I)
    END IF
    IF(MINCOL .GT. NXCOL2(I)) THEN
        MINCOL = NXCOL2(I)
    END IF
END DO
IF(MINCOL.EQ.0)  MINCOL=1   ! 2014_08_20 . SCB

ALLOCATE(APONE(NASSEM))
ALLOCATE(APTWO(NASSEM))
ALLOCATE(CORNERPOS(NXROD,MAXCOL))
ALLOCATE(ASSEMCONTROL(NASSEM,7))
ALLOCATE(ORIGINCR(NG,NXY,NZ,NTYPE2))
ALLOCATE(PPMCR(NG,NXY,NZ,NTYPE2))
ALLOCATE(DMDCR(NG,NXY,NZ,NTYPE2))

CORNERPOS(:,:)      = 0
ASSEMCONTROL(:,:)   = 0
ORIGINCR(:,:,:,:)   = 0.
PPMCR(:,:,:,:)      = 0.
DMDCR(:,:,:,:)      = 0.

END SUBROUTINE