SUBROUTINE SCANCOMP(INDEV,IC)

USE MASTERXSL
USE PARAM      
  
INCLUDE 'GLOBAL.H'
INCLUDE 'CARDS.H'
INCLUDE 'XSEC.H'

INTEGER INDEV,IC
REAL::TEMP

CALL SKIP(INDEV,5)
READ(INDEV,*) NBURN(IC),NDER(IC),NDMOD(IC),NADF(IC),NDUM(IC)
READ(INDEV,*) RPPM(IC),RTF(IC),RTM(IC),RDM(IC),RPRESS(IC),TEMP

RTF(IC) = SQRT(RTF(IC)+CKELVIN)
RDM(IC) = RDM(IC)*1000.

END SUBROUTINE