SUBROUTINE SCANCCR(INDEV)

USE PARAM
USE MASTERXSL 

INCLUDE 'GLOBAL.H'     
INCLUDE 'FILES.H'
INCLUDE 'CARDS.H'      
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'GEOMH.H'
INCLUDE 'GEOMHFC.H'
INCLUDE 'ITRCNTL.H'  
INCLUDE 'FF.H'    
INCLUDE 'THCNTL.INC'
INCLUDE 'PERTURB.INC'
INCLUDE 'THLINK.INC' ! FREK/MARS


INTEGER,INTENT(IN)::INDEV
INTEGER::NXCOL,IASCII
INTEGER,DIMENSION(512)::IONEROW
LOGICAL::IFNUMERIC

NXRAD = 2*NRING+1
NXROD = 2*NXRAD+2

CALL RODALLOC1

IR    = 0
DO WHILE(IR .LT. NXROD)
    READ(INDEV,'(A512)') ONELINE
    NXCOL=NFIELDS(ONELINE)
    IF(SC(1).EQ.'!' .OR. NXCOL.EQ.0) GO TO 200 !SKIP A LINE
    DO I=1,MXNCOL
        IF(SC(I) .NE. ' ') THEN
            IASCII = ICHAR(SC(I))
            IF((IASCII-48)*(IASCII-57) .LE. 0) THEN
                GO TO 100 !NUMERIC
            ELSE
                BACKSPACE(INDEV)
                GO TO 300 !STRING
            ENDIF
        END IF
    END DO
100 CONTINUE
    IR = IR+1
    NXCOL2(IR) = NXCOL
    READ(ONELINE,*) (IONEROW(IC),IC=1,NXCOL)
    NCORNERCR = NCORNERCR + NXCOL
200 CONTINUE
ENDDO

300 CONTINUE

IRODS(1) = 1
IRODE(1) = 4
DO I=2,NXRAD
    IRODS(I) = IRODS(I-1) + 2
    IRODE(I) = IRODE(I-1) + 2
END DO

END SUBROUTINE