SUBROUTINE SCANXSL(indev)

USE MASTERXSL
!USE TEMP_BURNUP
USE PARAM

INCLUDE 'GLOBAL.H'
INCLUDE 'BENCH.H'
INCLUDE 'XSEC.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'CARDS.H'

CHARACTER NAME*20
INTEGER CNUM,NAXIAL,NRADIAL

CNUM    = 0
NAXIAL  = 0
NRADIAL = 0

DO WHILE(.TRUE.)
    READ(INDEV,'(A512)',END=1000) ONELINE
    IF(PROBE.EQ.DOT .OR. PROBE.EQ.SLASH) EXIT
    IF(PROBE.EQ.'-' .OR. PROBE.EQ.BANG .OR. ONELINE.EQ.BLANK .OR. IFNUMERIC(ONELINE)) CYCLE
    READ(ONELINE,*) CARDNAME
    CALL TOUPPER(CARDNAME)
    SELECT CASE(CARDNAME)
        CASE('REFL')
            READ(INDEV,*) ONELINE
            READ(ONELINE,*) CARDNAME
            SELECT CASE(CARDNAME)
                CASE('AXIAL')
                    NAXIAL=NAXIAL+1
                CASE('RADIAL')
                    NRADIAL=NRADIAL+1
            END SELECT
        CASE('COMP')
            CNUM=CNUM+1
        CASE DEFAULT
            GOTO 100
    END SELECT
100 CONTINUE
END DO

NAXIAL = 2   ! 2014_08_07 . SCB
NRADIAL = 3  ! 2014_08_07 . SCB

1000 CONTINUE
CALL MAS_ALLOC1(CNUM,NAXIAL,NRADIAL)
REWIND(INDEV)
MASCOM = CNUM
CNUM=0

DO WHILE(.TRUE.)
    READ(INDEV,'(A512)',END=2000) ONELINE
    IF(PROBE.EQ.DOT .OR. PROBE.EQ.SLASH) EXIT
    IF(PROBE.EQ.'-' .OR. PROBE.EQ.BANG .OR. ONELINE.EQ.BLANK .OR. IFNUMERIC(ONELINE)) CYCLE
    READ(ONELINE,*) CARDNAME,NAME
    CALL TOUPPER(CARDNAME)
    SELECT CASE(CARDNAME)
        CASE('REFL')
            CALL READREFL(INDEV)
        CASE('COMP')
            CNUM=CNUM+1
            CNAME(CNUM) = NAME
            call toupper(CNAME(CNUM))   ! 2014_07_23 . scb
            CALL SCANCOMP(INDEV,CNUM)
        CASE DEFAULT
            GOTO 200
    END SELECT
200 CONTINUE
END DO

2000 CONTINUE
CALL MAS_ALLOC2(CNUM)
CALL NUTYP
REWIND(INDEV)
CNUM=0

DO WHILE(.TRUE.)
    READ(INDEV,'(A512)',END=3000) ONELINE
    IF(PROBE.EQ.DOT .OR. PROBE.EQ.SLASH) EXIT
    IF(PROBE.EQ.'-' .OR. PROBE.EQ.BANG .OR. ONELINE.EQ.BLANK .OR. IFNUMERIC(ONELINE)) CYCLE
    READ(ONELINE,*) CARDNAME,NAME
    CALL TOUPPER(CARDNAME)
    SELECT CASE(CARDNAME)
        CASE('REFL')
            GOTO 300
        CASE('COMP')
            CNUM=CNUM+1
            CALL READCOMP(INDEV,CNUM)
            BACKSPACE(INDEV)
        CASE DEFAULT
            GOTO 300
    END SELECT
300 CONTINUE
END DO

3000 CONTINUE

END SUBROUTINE