SUBROUTINE MAS2DEP

USE PARAM
USE TIMER
USE MASTERXSL
USE DEPLMOD
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB
USE ALLOCS

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
INCLUDE 'FILES.H'
INCLUDE 'XESM.H'  ! 2013_09_27 . SCB
INCLUDE 'FFDM.H'

! GET THE NUMBER DENSITY(ND) INFORMATION FROM MASTERXSL TO DEPLMOD
! IN MAS, THE ND WAS SAVED AS COMPOSITION AND ID
! IN DEP, THE ND SHOULD BE SAVED AS GEOMETRY AND ID

DO IZ=1,NZ
  DO IXY=1,NXY
    KA    = KTOKA(IZ)
    IAT   = IASSYTYP(IXY)
    ICOMP = ICOMPNUMZ(KA,IAT)
    DO IN=1,NUCNUM
      ATOM0(IXY,IZ,IN) = NUCND_T(ICOMP,IN)
!      if(in.eq.14) ATOM0(IXY,IZ,IN) = 0.
    END DO
  END DO
END DO

END SUBROUTINE