SUBROUTINE PCKNFX(IXY,IZ)

USE PARAM
USE TIMER
USE MASTERXSL
USE DEPLMOD
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB
USE ALLOCS

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
INCLUDE 'FILES.H'
INCLUDE 'XESM.H'  ! 2013_09_27 . SCB
INCLUDE 'FFDM.H'
INCLUDE 'POW.H'

LOGICAL::FIRST=.TRUE.
INTEGER::KA,IAT,ICOMP
INTEGER,INTENT(IN)::IXY,IZ

!     INITIALIZE DEPLETED (NEW) NUCLIDE NUMBER DENSITIES AS OLD ONES
!     FOR THE NON-DEPLETED NUCLIDES

KA    = KTOKA(IZ)
IAT   = IASSYTYP(IXY)
ICOMP = ICOMPNUMZ(KA,IAT)

DO IN = 1, MNUCL
    ATI(IN) = ATOM0(IXY,IZ,IN)
    ATD(IN) = ATOM0(IXY,IZ,IN)
ENDDO

!       FLUX

DO IG = 1, NG
    FLX(IG) = DEP_PHI(IG,IXY,IZ)
ENDDO

!       XS

DO IG = 1, NG
    DO IN = 1, MNUCL
        DEPLXSA(IG,IN) = NODEMICXS(IXY,IZ,ABSO,IN,IG)
        DEPLXSF(IG,IN) = NODEMICXS(IXY,IZ,FISS,IN,IG)
        DEPLXSK(IG,IN) = NODEMICXS(IXY,IZ,KAPA,IN,IG)
        DEPLXSC(IG,IN) = NODEMICXS(IXY,IZ,CAPT,IN,IG)
    ENDDO
ENDDO

!   (N,2N) REACTION RATE IS CONSIDERED.

XSN2N=0.
TN2N =0.


!      XSN2N=6.E-3
!      XSN2N=5.2E-3
!      XSN2N=3.42E-3

      N2NP=NUCSRCH('U238',MNUCL)
      DEPLXSC(1,N2NP)=DEPLXSC(1,N2NP)+XSN2N
      TN2N=XSN2N*FLX(1)*1.0D-24

!   CALCULATE CAPTURE, REMOVAL, DECAY AND FISSION RATE OF NUCLIDES

DO IN = 1, MNUCL
    CAP(IN) = 0.0
    REM(IN) = 0.0
    FIS(IN) = 0.0
    DO IG = 1, NG
        CAP(IN) = CAP(IN) + DEPLXSC(IG,IN)*FLX(IG)
        REM(IN) = REM(IN) + DEPLXSA(IG,IN)*FLX(IG)
        FIS(IN) = FIS(IN) + DEPLXSF(IG,IN)*FLX(IG)
    ENDDO
    CAP(IN) = CAP(IN)*1.0D-24
    REM(IN) = REM(IN)*1.0D-24
    FIS(IN) = FIS(IN)*1.0D-24
    DCY(IN) = DCNST(IN)
    REM(IN) = REM(IN) + DCNST(IN)
ENDDO

! for the test
!rem(22) = 0.
RETURN

END SUBROUTINE