SUBROUTINE RATEK()

USE PARAM
USE TIMER
USE MASTERXSL
USE DEPLMOD
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB
USE ALLOCS

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
INCLUDE 'FILES.H'
INCLUDE 'XESM.H'  ! 2013_09_27 . SCB
INCLUDE 'FFDM.H'
INCLUDE 'POW.H'

RKF = 0.
DO IG=1,NG
    DO K=1,NZ
        DO IXY=1,NXY
            RKF = RKF + XSKPF(IG,IXY,K)*PHIF(IG,IXY,K)*VOLNODE(IXY,K)
        END DO
    END DO
END DO

END SUBROUTINE