SUBROUTINE MIC2MAC_N2A(IC,ICOMP)

USE PARAM
USE TIMER
USE MASTERXSL
!USE TEMP_BURNUP
USE DECUSPING1N,  ONLY : XSSET ! 2012_09_28 . SCB
use readN2A,      only : assm, MACX_ID,nufis, fs, tr, sct, ab, kap, maxnb,MAXDMOD,MAXBORON,MAXTFUEL,MAXTMOD

INCLUDE 'GLOBAL.H'
INCLUDE 'TIMES.H'
INCLUDE 'XSEC.H'
INCLUDE 'GEOM.H'
INCLUDE 'SRCHPPM.H'
INCLUDE 'THFDBK.INC'
INCLUDE 'THFUEL.INC'
INCLUDE 'THCNTL.INC'
INCLUDE 'THGEOM.INC'
INCLUDE 'THOP.INC'
! ADDED IN ARTOS VER. 0.2 . 2012_07_11 BY SCB.
INCLUDE 'FILES.H'
!      INCLUDE 'MSLB.INC' ! MSLB
! ADDED END     
INCLUDE 'XESM.H'  ! 2013_09_27 . SCB

INTEGER,INTENT(IN)::IC,ICOMP
!REAL::FCONV,TEMP,FACT,FACT2
INTEGER::ID                      ! 2016.9.10. jjh
REAL::FCONV,TEMP,FACT,FACT2,TEMP1(maxnb),TEMP2(3),TEMP3(3,maxdmod)
real(8):: d_ppm, tmp1, tmp2, tmp3

IF(NG .EQ. 2) THEN
    SIGSMS(1,ICOMP) = 1
    SIGSMS(2,ICOMP) = 1
    SIGSME(1,ICOMP) = 2
    SIGSME(2,ICOMP) = 2
END IF

! 2016.9.22. jjh

TEMP = MACORIGIN(ICOMP,SCA,1)
MACORIGIN(ICOMP,SCA,1) = MACORIGIN(ICOMP,SCA,2)
MACORIGIN(ICOMP,SCA,2) = TEMP
!MACORIGIN(ICOMP,SCA,1) = 0.
TEMP = ORIGINXS(ICOMP,SCA,IH2O,1)
ORIGINXS(ICOMP,SCA,IH2O,1) = ORIGINXS(ICOMP,SCA,IH2O,2)
ORIGINXS(ICOMP,SCA,IH2O,2) = TEMP
!ORIGINXS(ICOMP,SCA,IH2O,1) = 0.
TEMP = ORIGINXS(ICOMP,SCA,IB10,1)
ORIGINXS(ICOMP,SCA,IB10,1) = ORIGINXS(ICOMP,SCA,IB10,2)
ORIGINXS(ICOMP,SCA,IB10,2) = TEMP
!ORIGINXS(ICOMP,SCA,IB10,1) = 0.
! 2014_07_28 . pkb
TEMP = ORIGINXS(ICOMP,SCA,ICRD,1)
ORIGINXS(ICOMP,SCA,ICRD,1) = ORIGINXS(ICOMP,SCA,ICRD,2)
ORIGINXS(ICOMP,SCA,ICRD,2) = TEMP
!ORIGINXS(ICOMP,SCA,ICRD,1) = 0.

! 2014_08_20 . pkb
!TEMP = OCRDXS(ICOMP,SCA,1,1)
!OCRDXS(ICOMP,SCA,2,1) = TEMP
!OCRDXS(ICOMP,SCA,1,1) = 0.

! added end
TEMP2 = OCRDXS(ICOMP,SCA,1,:)
OCRDXS(ICOMP,SCA,1,:) = OCRDXS(ICOMP,SCA,2,:)
OCRDXS(ICOMP,SCA,2,:) = TEMP2
!OCRDXS(ICOMP,SCA,1,:) = 0.
! added end
! 2014_08_20 . PKB
TEMP2 = PPMDXS_H(ICOMP,SCA,1,:)
PPMDXS_H(ICOMP,SCA,1,:) = PPMDXS_H(ICOMP,SCA,2,:)
PPMDXS_H(ICOMP,SCA,2,:) = TEMP2
!PPMDXS_H(ICOMP,SCA,1,:) = 0.
TEMP3 = DMDXS_H(ICOMP,SCA,1,:,:)
DMDXS_H(ICOMP,SCA,1,:,:) = DMDXS_H(ICOMP,SCA,2,:,:)
DMDXS_H(ICOMP,SCA,2,:,:) = TEMP3
!DMDXS_H(ICOMP,SCA,1,:,ID) = 0.
!ADDED END

TEMP1 = MACDPPM(ICOMP,SCA,1,:)
MACDPPM(ICOMP,SCA,1,:) = MACDPPM(ICOMP,SCA,2,:)
MACDPPM(ICOMP,SCA,2,:) = TEMP1
!MACDPPM(ICOMP,SCA,1) = 0.
TEMP1 = PPMDXS(ICOMP,SCA,IH2O,1,:)
PPMDXS(ICOMP,SCA,IH2O,1,:) = PPMDXS(ICOMP,SCA,IH2O,2,:)
PPMDXS(ICOMP,SCA,IH2O,2,:) = TEMP1
!PPMDXS(ICOMP,SCA,IH2O,1) = 0.
TEMP1 = PPMDXS(ICOMP,SCA,IB10,1,:)
PPMDXS(ICOMP,SCA,IB10,1,:) = PPMDXS(ICOMP,SCA,IB10,2,:)
PPMDXS(ICOMP,SCA,IB10,2,:) = TEMP1
!PPMDXS(ICOMP,SCA,IB10,1) = 0.
! 2014_07_28 . pkb
TEMP1 = PPMDXS(ICOMP,SCA,ICRD,1,:)
PPMDXS(ICOMP,SCA,ICRD,1,:) = PPMDXS(ICOMP,SCA,ICRD,2,:)
PPMDXS(ICOMP,SCA,ICRD,2,:) = TEMP1
!PPMDXS(ICOMP,SCA,ICRD,1) = 0.
! added end

TEMP1 = MACDTF(ICOMP,SCA,1,:)
MACDTF(ICOMP,SCA,1,:) = MACDTF(ICOMP,SCA,2,:)
MACDTF(ICOMP,SCA,2,:) = TEMP1
!MACDTF(ICOMP,SCA,1) = 0.
TEMP1 = TFDXS(ICOMP,SCA,IH2O,1,:)
TFDXS(ICOMP,SCA,IH2O,1,:) = TFDXS(ICOMP,SCA,IH2O,2,:)
TFDXS(ICOMP,SCA,IH2O,2,:) = TEMP1
!TFDXS(ICOMP,SCA,IH2O,1) = 0.
TEMP1 = TFDXS(ICOMP,SCA,IB10,1,:)
TFDXS(ICOMP,SCA,IB10,1,:) = TFDXS(ICOMP,SCA,IB10,2,:)
TFDXS(ICOMP,SCA,IB10,2,:) = TEMP1
!TFDXS(ICOMP,SCA,IB10,1) = 0.
! 2014_07_28 . pkb
TEMP1 = TFDXS(ICOMP,SCA,ICRD,1,:)
TFDXS(ICOMP,SCA,ICRD,1,:) = TFDXS(ICOMP,SCA,ICRD,2,:)
TFDXS(ICOMP,SCA,ICRD,2,:) = TEMP1
!TFDXS(ICOMP,SCA,ICRD,1) = 0.
! added end

! 2016.10.10.  JJH
TEMP1 = MACDTM(ICOMP,SCA,1,:) 
MACDTM(ICOMP,SCA,1,:) = MACDTM(ICOMP,SCA,2,:)
MACDTM(ICOMP,SCA,2,:) = TEMP1
!MACDTM(ICOMP,SCA,1) = 0.
TEMP1 = TMDXS(ICOMP,SCA,IH2O,1,:)
TMDXS(ICOMP,SCA,IH2O,1,:) = TMDXS(ICOMP,SCA,IH2O,2,:)
TMDXS(ICOMP,SCA,IH2O,2,:) = TEMP1
!TMDXS(ICOMP,SCA,IH2O,1) = 0.
TEMP1 = TMDXS(ICOMP,SCA,IB10,1,:)
TMDXS(ICOMP,SCA,IB10,1,:) = TMDXS(ICOMP,SCA,IB10,2,:)
TMDXS(ICOMP,SCA,IB10,2,:) = TEMP1
!TMDXS(ICOMP,SCA,IB10,1) = 0.
! 2014_07_28 . pkb
TEMP1 = TMDXS(ICOMP,SCA,ICRD,1,:)
TMDXS(ICOMP,SCA,ICRD,1,:) = TMDXS(ICOMP,SCA,ICRD,2,:)
TMDXS(ICOMP,SCA,ICRD,2,:) = TEMP1
!TMDXS(ICOMP,SCA,ICRD,1) = 0.
! added end


! 2014_08_05 . pkb
TEMP1 = MACDDM(ICOMP,SCA,1,:)
MACDDM(ICOMP,SCA,1,:) = MACDDM(ICOMP,SCA,2,:)
MACDDM(ICOMP,SCA,2,:) = TEMP1
!MACDDM(ICOMP,SCA,1,:) = 0.
TEMP1 = DMDXS(ICOMP,SCA,IH2O,1,:)
DMDXS(ICOMP,SCA,IH2O,1,:) = DMDXS(ICOMP,SCA,IH2O,2,:)
DMDXS(ICOMP,SCA,IH2O,2,:) = TEMP1
!DMDXS(ICOMP,SCA,IH2O,1,:) = 0.
TEMP1 = DMDXS(ICOMP,SCA,IB10,1,:)
DMDXS(ICOMP,SCA,IB10,1,:) = DMDXS(ICOMP,SCA,IB10,2,:)
DMDXS(ICOMP,SCA,IB10,2,:) = TEMP1
!DMDXS(ICOMP,SCA,IB10,1,:) = 0.
TEMP1 = DMDXS(ICOMP,SCA,ICRD,1,:)
DMDXS(ICOMP,SCA,ICRD,1,:) = DMDXS(ICOMP,SCA,ICRD,2,:)
DMDXS(ICOMP,SCA,ICRD,2,:) = TEMP1
!DMDXS(ICOMP,SCA,ICRD,1,:) = 0.
! added end


!NUCND_T(IC,IH2O)=0.d0   ! 2014_08_01 . scb for dbg

!----------------------- H2O AND B10 NUMBER DENSITY -----------------------
! Previous Version
!FACT  = 3.2992605E-07
!FACT2 = PPM * FACT
!NUCND_T(IC,IB10) = NUCND_T(IC,IH2O)*FACT2

! JJH Version
!FACT  = 2.38725e-8
B10_ppm=0._8
NUCND_T(IC,IB10) = assm(ic)%nuclei(ib10)%nd(1)
B10_ppm = NUCND_T(IC,IB10)/basecond(dppm)
!--------------------------------------------------------------------------

!----------------------------- ADFs CONDITION -----------------------------



!----------------------------- BASE CONDITION -----------------------------   ! 2016.9.22. jjh
DO IG=1,NG  
    SIGTR(IG,ICOMP)  = MACORIGIN(ICOMP,TRAN,IG) &
                       !+ ORIGINXS(ICOMP,TRAN,IH2O,IG)*NUCND_T(IC,IH2O) + ORIGINXS(ICOMP,TRAN,IB10,IG)*NUCND_T(IC,IB10) &
                       + ORIGINXS(ICOMP,TRAN,IPM,IG)*NUCND_T(IC,IPM) + ORIGINXS(ICOMP,TRAN,ISM,IG)*NUCND_T(IC,ISM) &
                       + ORIGINXS(ICOMP,TRAN,II,IG)*NUCND_T(IC,II) + ORIGINXS(ICOMP,TRAN,IXE,IG)*NUCND_T(IC,IXE) &
                       + ORIGINXS(ICOMP,TRAN,ICRD,IG)*NUCND_T(IC,ICRD)
    SIGD(IG,ICOMP)   = 1/(3*SIGTR(IG,ICOMP))
    SIGA(IG,ICOMP)   = MACORIGIN(ICOMP,ABSO,IG) &
                       !+ ORIGINXS(ICOMP,ABSO,IH2O,IG)*NUCND_T(IC,IH2O) + ORIGINXS(ICOMP,ABSO,IB10,IG)*NUCND_T(IC,IB10) &
                       + ORIGINXS(ICOMP,ABSO,IPM,IG)*NUCND_T(IC,IPM) + ORIGINXS(ICOMP,ABSO,ISM,IG)*NUCND_T(IC,ISM) &
                       + ORIGINXS(ICOMP,ABSO,II,IG)*NUCND_T(IC,II) + ORIGINXS(ICOMP,ABSO,IXE,IG)*NUCND_T(IC,IXE) &
                       + ORIGINXS(ICOMP,ABSO,ICRD,IG)*NUCND_T(IC,ICRD)
    SIGNF(IG,ICOMP)  = MACORIGIN(ICOMP,NUFS,IG) &
                       !+ ORIGINXS(ICOMP,NUFS,IH2O,IG)*NUCND_T(IC,IH2O) + ORIGINXS(ICOMP,NUFS,IB10,IG)*NUCND_T(IC,IB10) &
                       + ORIGINXS(ICOMP,NUFS,IPM,IG)*NUCND_T(IC,IPM) + ORIGINXS(ICOMP,NUFS,ISM,IG)*NUCND_T(IC,ISM) &
                       + ORIGINXS(ICOMP,NUFS,II,IG)*NUCND_T(IC,II) + ORIGINXS(ICOMP,NUFS,IXE,IG)*NUCND_T(IC,IXE) &
                       + ORIGINXS(ICOMP,NUFS,ICRD,IG)*NUCND_T(IC,ICRD)
    SIGKF(IG,ICOMP)  = MACORIGIN(ICOMP,KAPA,IG) &
                       !+ ORIGINXS(ICOMP,KAPA,IH2O,IG)*NUCND_T(IC,IH2O) + ORIGINXS(ICOMP,KAPA,IB10,IG)*NUCND_T(IC,IB10) &
                       + ORIGINXS(ICOMP,KAPA,IPM,IG)*NUCND_T(IC,IPM) + ORIGINXS(ICOMP,KAPA,ISM,IG)*NUCND_T(IC,ISM) &
                       + ORIGINXS(ICOMP,KAPA,II,IG)*NUCND_T(IC,II) + ORIGINXS(ICOMP,KAPA,IXE,IG)*NUCND_T(IC,IXE) &
                       + ORIGINXS(ICOMP,KAPA,ICRD,IG)*NUCND_T(IC,ICRD)
    SIGF(IG,ICOMP)   = MACORIGIN(ICOMP,FISS,IG) &
                       !+ ORIGINXS(ICOMP,FISS,IH2O,IG)*NUCND_T(IC,IH2O) + ORIGINXS(ICOMP,FISS,IB10,IG)*NUCND_T(IC,IB10) &
                       + ORIGINXS(ICOMP,FISS,IPM,IG)*NUCND_T(IC,IPM) + ORIGINXS(ICOMP,FISS,ISM,IG)*NUCND_T(IC,ISM) &
                       + ORIGINXS(ICOMP,FISS,II,IG)*NUCND_T(IC,II) + ORIGINXS(ICOMP,FISS,IXE,IG)*NUCND_T(IC,IXE) &
                       + ORIGINXS(ICOMP,FISS,ICRD,IG)*NUCND_T(IC,ICRD)    
    
   DO MS=1,NG
        IF(MS .EQ. IG) THEN
!            CONTINUE
        ELSE
!          SIGSM(IG,MS,ICOMP)=assm(icomp)%nuclei(MACX_ID)%xsec(sct)%basexs(1,ig)
          
          SIGSM(MS,IG,ICOMP) = MACORIGIN(ICOMP,SCA,IG) &
                       !+ ORIGINXS(ICOMP,SCA,IH2O,IG)*NUCND_T(IC,IH2O) + ORIGINXS(ICOMP,SCA,IB10,IG)*NUCND_T(IC,IB10) &
                       + ORIGINXS(ICOMP,SCA,IPM,IG)*NUCND_T(IC,IPM) + ORIGINXS(ICOMP,SCA,ISM,IG)*NUCND_T(IC,ISM) &
                       + ORIGINXS(ICOMP,SCA,II,IG)*NUCND_T(IC,II) + ORIGINXS(ICOMP,SCA,IXE,IG)*NUCND_T(IC,IXE) &
                       + ORIGINXS(ICOMP,SCA,ICRD,IG)*NUCND_T(IC,ICRD)
          
          !            SIGSM(MS,IG,ICOMP) = MACORIGIN(ICOMP,SCA,IG)
        END IF
    END DO
END DO

SIGCHI(1,ICOMP) = 1.
SIGCHI(2,ICOMP) = 0.
!----------------------------- ADF DERIVATIVES ----------------------------   ! ??????????? why id?

  DO IG=1,NG
      DADFACTOR0(DPPM,:,IG,ICOMP) = PPMDADF(ICOMP,IG,:)
      DADFACTOR0(DTF,:,IG,ICOMP)  = TFDADF(ICOMP,IG,:)
      DADFACTOR0(DTM,:,IG,ICOMP)  = TMDADF(ICOMP,IG,:)
      DADFACTOR0(DDM,:,IG,ICOMP)  = DMDADF(ICOMP,IG,:)   ! 2014_08_06 . PKB
  END DO

!----------------------------- PPM DERIVATIVES ----------------------------
  
do id=1, nboron(icomp)
  DO IG=1,NG

    DSIGD_TR1(DPPM,ID,IG,ICOMP) = MACDPPM(ICOMP,TRAN,IG,id) & 
                            !+ PPMDXS(ICOMP,TRAN,IH2O,IG)*NUCND_T(IC,IH2O) + PPMDXS(ICOMP,TRAN,IB10,IG)*NUCND_T(IC,IB10)  &
                            + PPMDXS(ICOMP,TRAN,IPM,IG,id)*NUCND_T(IC,IPM) + PPMDXS(ICOMP,TRAN,ISM,IG,id)*NUCND_T(IC,ISM) &
                            + PPMDXS(ICOMP,TRAN,II,IG,id)*NUCND_T(IC,II) + PPMDXS(ICOMP,TRAN,IXE,IG,id)*NUCND_T(IC,IXE) &
                            + PPMDXS(ICOMP,TRAN,ICRD,IG,id)*NUCND_T(IC,ICRD)
    DSIGT_A1(DPPM,ID,IG,ICOMP)  = MACDPPM(ICOMP,ABSO,IG,id) &
                            !+ PPMDXS(ICOMP,ABSO,IH2O,IG)*NUCND_T(IC,IH2O) + PPMDXS(ICOMP,ABSO,IB10,IG)*NUCND_T(IC,IB10) &
                            + PPMDXS(ICOMP,ABSO,IPM,IG,id)*NUCND_T(IC,IPM) + PPMDXS(ICOMP,ABSO,ISM,IG,id)*NUCND_T(IC,ISM) &
                            + PPMDXS(ICOMP,ABSO,II,IG,id)*NUCND_T(IC,II) + PPMDXS(ICOMP,ABSO,IXE,IG,id)*NUCND_T(IC,IXE) &
                            + PPMDXS(ICOMP,ABSO,ICRD,IG,id)*NUCND_T(IC,ICRD)
    DSIGNF1(DPPM,ID,IG,ICOMP)   = MACDPPM(ICOMP,NUFS,IG,id) &
                            !+ PPMDXS(ICOMP,NUFS,IH2O,IG)*NUCND_T(IC,IH2O) + PPMDXS(ICOMP,NUFS,IB10,IG)*NUCND_T(IC,IB10) &
                            + PPMDXS(ICOMP,NUFS,IPM,IG,id)*NUCND_T(IC,IPM) + PPMDXS(ICOMP,NUFS,ISM,IG,id)*NUCND_T(IC,ISM) &
                            + PPMDXS(ICOMP,NUFS,II,IG,id)*NUCND_T(IC,II) + PPMDXS(ICOMP,NUFS,IXE,IG,id)*NUCND_T(IC,IXE) &
                            + PPMDXS(ICOMP,NUFS,ICRD,IG,id)*NUCND_T(IC,ICRD)
    DSIGKF1(DPPM,ID,IG,ICOMP)   = MACDPPM(ICOMP,KAPA,IG,id) &
                            !+ PPMDXS(ICOMP,KAPA,IH2O,IG)*NUCND_T(IC,IH2O) + PPMDXS(ICOMP,KAPA,IB10,IG)*NUCND_T(IC,IB10) &
                            + PPMDXS(ICOMP,KAPA,IPM,IG,id)*NUCND_T(IC,IPM) + PPMDXS(ICOMP,KAPA,ISM,IG,id)*NUCND_T(IC,ISM) &
                            + PPMDXS(ICOMP,KAPA,II,IG,id)*NUCND_T(IC,II) + PPMDXS(ICOMP,KAPA,IXE,IG,id)*NUCND_T(IC,IXE) &
                            + PPMDXS(ICOMP,KAPA,ICRD,IG,id)*NUCND_T(IC,ICRD)
    DSIGF1(DPPM,ID,IG,ICOMP)    = MACDPPM(ICOMP,FISS,IG,id) &
                            !+ PPMDXS(ICOMP,FISS,IH2O,IG)*NUCND_T(IC,IH2O) + PPMDXS(ICOMP,FISS,IB10,IG)*NUCND_T(IC,IB10) &
                            + PPMDXS(ICOMP,FISS,IPM,IG,id)*NUCND_T(IC,IPM) + PPMDXS(ICOMP,FISS,ISM,IG,id)*NUCND_T(IC,ISM) &
                            + PPMDXS(ICOMP,FISS,II,IG,id)*NUCND_T(IC,II) + PPMDXS(ICOMP,FISS,IXE,IG,id)*NUCND_T(IC,IXE) &
                            + PPMDXS(ICOMP,FISS,ICRD,IG,id)*NUCND_T(IC,ICRD)    
    
    DO MS=1,NG
        IF(MS .EQ. IG) THEN
!            CONTINUE
        ELSE
           DSIGSM1(MS,DPPM,ID,IG,ICOMP) = MACDPPM(ICOMP,SCA,IG,id) &
                                    !+ PPMDXS(ICOMP,SCA,IH2O,IG)*NUCND_T(IC,IH2O) + PPMDXS(ICOMP,SCA,IB10,IG)*NUCND_T(IC,IB10) &
                                    + PPMDXS(ICOMP,SCA,IPM,IG,id)*NUCND_T(IC,IPM) + PPMDXS(ICOMP,SCA,ISM,IG,id)*NUCND_T(IC,ISM) &
                                    + PPMDXS(ICOMP,SCA,II,IG,id)*NUCND_T(IC,II) + PPMDXS(ICOMP,SCA,IXE,IG,id)*NUCND_T(IC,IXE) &
                                    + PPMDXS(ICOMP,SCA,ICRD,IG,id)*NUCND_T(IC,ICRD)
            !DSIGSM(MS,DPPM,IG,ICOMP) = MACDPPM(ICOMP,SCA,IG)   ! 2014_08_05 . scb for dbg
        END IF
    END DO
  END DO
end do


!--------------------------- FUEL TEMP DERIVATIVES ------------------------

do id=1, ntfuel(icomp)
  DO IG=1,NG
    DSIGD_TR1(DTF,ID,IG,ICOMP) = MACDTF(ICOMP,TRAN,IG,id) !& 
                           !+ TFDXS(ICOMP,TRAN,IH2O,IG)*NUCND_T(IC,IH2O) + TFDXS(ICOMP,TRAN,IB10,IG)*NUCND_T(IC,IB10)
    DSIGT_A1(DTF,ID,IG,ICOMP)  = MACDTF(ICOMP,ABSO,IG,id) !&
                           !+ TFDXS(ICOMP,ABSO,IH2O,IG)*NUCND_T(IC,IH2O) + TFDXS(ICOMP,ABSO,IB10,IG)*NUCND_T(IC,IB10)
    DSIGNF1(DTF,ID,IG,ICOMP)   = MACDTF(ICOMP,NUFS,IG,id) !&
                           !+ TFDXS(ICOMP,NUFS,IH2O,IG)*NUCND_T(IC,IH2O) + TFDXS(ICOMP,NUFS,IB10,IG)*NUCND_T(IC,IB10)
    DSIGKF1(DTF,ID,IG,ICOMP)   = MACDTF(ICOMP,KAPA,IG,id) !&                                          
                           !+ TFDXS(ICOMP,KAPA,IH2O,IG)*NUCND_T(IC,IH2O) + TFDXS(ICOMP,KAPA,IB10,IG)*NUCND_T(IC,IB10)
    DSIGF1(DTF,ID,IG,ICOMP)    = MACDTF(ICOMP,FISS,IG,id) !&                                       
                           !+ TFDXS(ICOMP,FISS,IH2O,IG)*NUCND_T(IC,IH2O) + TFDXS(ICOMP,FISS,IB10,IG)*NUCND_T(IC,IB10)   ! 2014_07_31 . SCB
    DO MS=1,NG
        IF(MS .EQ. IG) THEN
!            CONTINUE
        ELSE
            DSIGSM1(MS,DTF,ID,IG,ICOMP) = MACDTF(ICOMP,SCA,IG,id) !&
                                    !+ TFDXS(ICOMP,SCA,IH2O,IG)*NUCND_T(IC,IH2O) + TFDXS(ICOMP,SCA,IB10,IG)*NUCND_T(IC,IB10)
!            DSIGSM(2,DTF,2,ICOMP)   = 0.   ! 2016.10.7. jjh
            
            !DSIGSM(MS,DTF,IG,ICOMP) = MACDTF(ICOMP,SCA,IG)   ! 2014_08_05 . scb for dbg
        END IF
    END DO
  END DO
end do

!--------------------------- MOD TEMP DERIVATIVES ------------------------
do id=1, ntmod(icomp)
  DO IG=1,NG
    DSIGD_TR1(DTM,ID,IG,ICOMP) = MACDTM(ICOMP,TRAN,IG,id) !+& 
                             !TMDXS(ICOMP,TRAN,IH2O,IG)*NUCND_T(IC,IH2O) + TMDXS(ICOMP,TRAN,IB10,IG)*NUCND_T(IC,IB10)
    DSIGT_A1(DTM,ID,IG,ICOMP)  = MACDTM(ICOMP,ABSO,IG,id) !+&
                             !TMDXS(ICOMP,ABSO,IH2O,IG)*NUCND_T(IC,IH2O) + TMDXS(ICOMP,ABSO,IB10,IG)*NUCND_T(IC,IB10)
    DSIGNF1(DTM,ID,IG,ICOMP)   = MACDTM(ICOMP,NUFS,IG,id) !+&                                       
                             !TMDXS(ICOMP,NUFS,IH2O,IG)*NUCND_T(IC,IH2O) + TMDXS(ICOMP,NUFS,IB10,IG)*NUCND_T(IC,IB10)
    DSIGKF1(DTM,ID,IG,ICOMP)   = MACDTM(ICOMP,KAPA,IG,id) !+&                                          
                             !TMDXS(ICOMP,KAPA,IH2O,IG)*NUCND_T(IC,IH2O) + TMDXS(ICOMP,KAPA,IB10,IG)*NUCND_T(IC,IB10)
    DSIGF1(DTM,ID,IG,ICOMP)   = MACDTM(ICOMP,FISS,IG,id) !+&                                       
                             !TMDXS(ICOMP,FISS,IH2O,IG)*NUCND_T(IC,IH2O) + TMDXS(ICOMP,FISS,IB10,IG)*NUCND_T(IC,IB10)   ! 2014_07_31 . SCB
    DO MS=1,NG
        IF(MS .EQ. IG) THEN
!            CONTINUE
        ELSE
            DSIGSM1(MS,DTM,ID,IG,ICOMP) = MACDTM(ICOMP,SCA,IG,id)! +&
                                      !TMDXS(ICOMP,SCA,IH2O,IG)*NUCND_T(IC,IH2O) + TMDXS(ICOMP,SCA,IB10,IG)*NUCND_T(IC,IB10)
!            DSIGSM(2,DTM,2,ICOMP)   = 0.   ! 2016.10.7. jjh
            
            !DSIGSM(MS,DTF,IG,ICOMP) = MACDTF(ICOMP,SCA,IG)   ! 2014_08_05 . scb for dbg
        END IF
    END DO
  END DO
end do
!--------------------------- MOD DENS DERIVATIVES ------------------------
! 2014_08_05 . pkb

!fconv=1.e-3
do id=1, ndmod(icomp)
  DO IG=1,NG  
    DSIGD_TR1(DDM,ID,IG,ICOMP) = MACDDM(ICOMP,TRAN,IG,ID)! +&
                             !DMDXS(ICOMP,TRAN,IH2O,IG,1)*NUCND_T(IC,IH2O) + DMDXS(ICOMP,TRAN,IB10,IG,1)*NUCND_T(IC,IB10)                             
    DSIGT_A1(DDM,ID,IG,ICOMP)  = MACDDM(ICOMP,ABSO,IG,ID) !+&
                             !DMDXS(ICOMP,ABSO,IH2O,IG,1)*NUCND_T(IC,IH2O) + DMDXS(ICOMP,ABSO,IB10,IG,1)*NUCND_T(IC,IB10)
    DSIGNF1(DDM,ID,IG,ICOMP)   = MACDDM(ICOMP,NUFS,IG,ID)! +&
                             !DMDXS(ICOMP,NUFS,IH2O,IG,1)*NUCND_T(IC,IH2O) + DMDXS(ICOMP,NUFS,IB10,IG,1)*NUCND_T(IC,IB10)
    DSIGKF1(DDM,ID,IG,ICOMP)   = MACDDM(ICOMP,KAPA,IG,ID)! +&
                             !DMDXS(ICOMP,KAPA,IH2O,IG,1)*NUCND_T(IC,IH2O) + DMDXS(ICOMP,KAPA,IB10,IG,1)*NUCND_T(IC,IB10)
    DSIGF1(DDM,ID,IG,ICOMP)    = MACDDM(ICOMP,FISS,IG,ID) !+&
                             !DMDXS(ICOMP,FISS,IH2O,IG,1)*NUCND_T(IC,IH2O) + DMDXS(ICOMP,FISS,IB10,IG,1)*NUCND_T(IC,IB10)
    
    DO MS=1,NG
        IF(MS .EQ. IG) THEN
!            CONTINUE
        ELSE
            DSIGSM1(MS,DDM,ID,IG,ICOMP) = MACDDM(ICOMP,SCA,IG,ID) !+&
                                      !DMDXS(ICOMP,SCA,IH2O,IG,1)*NUCND_T(IC,IH2O) + DMDXS(ICOMP,SCA,IB10,IG,1)*NUCND_T(IC,IB10)
                                                  
            !DSIGSM(MS,DDM,IG,ICOMP) = MACDDM(ICOMP,SCA,IG,ID)   ! 2014_08_05 . scb for dbg
        END IF
    END DO
  END DO
end do

END SUBROUTINE