	MODULE PRECISION

            INTEGER,  PARAMETER :: dp = SELECTED_REAL_KIND( 6,  37)
!            INTEGER,  PARAMETER :: dp = SELECTED_REAL_KIND(15, 307)
!            INTEGER,  PARAMETER :: dp = SELECTED_REAL_KIND(33,4931)
            REAL(dp), PARAMETER :: EPS_ROUND_OFF  = 1.E-07  
            REAL(dp), PARAMETER :: REAL_MIN_VALUE = 1.E-37

	END MODULE PRECISION

